services:
  jekyll:
    image: ruby:3
    command: ./run.sh
    working_dir: /usr/src/app
    ports:
      - 4000:4000
    environment:
      - JEKYLL_ENV=production
    volumes:
      - .:/usr/src/app